---
- name: Ensure NixOS configuration folder present.
  file:
    path: /etc/nixos
    state: directory
    owner: root
    group: root
    mode: 0755
  register: nixos_conf_folder

- name: Ensure NixOS hardware-configuration.nix present.
  template:
    src: hardware-configuration.nix.j2
    dest: /etc/nixos/hardware-configuration.nix
    owner: root
    group: root
    lstrip_blocks: true
    trim_blocks: true
    mode: 644

- name: Ensure NixOS configuration.nix present.
  template:
    src: configuration.nix.j2
    dest: /etc/nixos/configuration.nix
    owner: root
    group: root
    lstrip_blocks: true
    trim_blocks: true
    mode: 644

- name: Ensure NixOS flake.nix present.
  template:
    src: flake.nix.j2
    dest: /etc/nixos/flake.nix
    owner: root
    group: root
    lstrip_blocks: true
    trim_blocks: true
    mode: 644