{ config, variables, ... }:

{
  users.groups = {
    ${variables.username} = { };
    docker = { };
  };
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."${variables.username}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "${variables.userHashedPassword}";
    home = "/home/${variables.username}";
    isNormalUser = true;
    description = "${variables.fullName}";
    extraGroups = [
      "${variables.username}" 
      "users"
      "networkmanager" 
      "wheel"
      "docker"
    ];
    #openssh.authorizedKeys.keys = [
    #  "TODO"
    #];
  };
}