# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a9add4de-e483-4aa5-8c6f-87443362dfa5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b7800a9a-3f57-4d81-a416-328dc4a03a5e".device = "/dev/disk/by-uuid/b7800a9a-3f57-4d81-a416-328dc4a03a5e";

  fileSystems."/home/snd/internal/500-gb" =
    { device = "/dev/disk/by-uuid/af90ce87-3830-4e94-ad6c-a6bc8e937893";
      fsType = "ext4";
    };
  
  # mit dieser Einstellung funktioniert der fn-Key auf meiner Keychron-K8
  boot.extraModprobeConfig = ''
    options hid_apple fnmode=2
  '';

  boot.initrd.luks.devices."internal-500-gb-ssd".device = "/dev/disk/by-uuid/500f7c70-6f52-410e-80d2-7a789de5d35d";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/B1E4-2125";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
