{ config, variables, ... }:

{
  users.groups = {
    tafka = { };
    docker = { };
  };
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.tafka = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "${config.age.secrets.tafka-e495-password.path}";
    home = "/home/${variables.username}";
    isNormalUser = true;
    description = "${variables.fullName}";
    extraGroups = [ 
      "${variables.username}" 
      "users"
      "networkmanager" 
      "wheel"
      "docker"
    ];
    #openssh.authorizedKeys.keys = [
    #  "TODO"
    #];
  };
}